### ISSUE TITLE
Lack of specified fullscreen resolution makes it unusable

### ISSUE THREAD

**Issue by Kyzer-dev** [0xC0000054/sc4-graphics-options#1]
It's not an issue of a DXWrapper or DGVoodoo. The game's UI is tiny above 1080p and completely unplayable for me. I don't want to manually switch my monitor to 1080p every time I want to play SimCity 4 on a whim.

Please add fullscreen resolution specification in the config file.

**Comment by 0xC0000054** [comment]
Unfortunately this isn't possible. 

SC4 appears to require that the window size match its internal render resolution. I had experimented with having a full screen window with a lower render resolution, but that produced a distorted image in-game.

You may be able to use an external app to upscale the game, e.g. https://github.com/Blinue/Magpie.
